apiVersion: apps/v1
kind: Deployment
metadata:
    name: example-blue
spec:
    selector:
        matchLabels:
            app: example
            env: blue
    replicas: 2
    template:
        metadata:
            labels:
                app: example
                env: blue
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Never
                  image: dipak
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: example-blue
spec:
    selector:
        app: example
        env: blue
    ports:
        - port: 5000
          targetPort: 5000      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
    - host: dipakparmar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-blue
                port:
                  number: 5000
         - path: /
            pathType: Prefix
            backend:
              service:
                name: example-green
                port:
                  number: 5000

