apiVersion: apps/v1
kind: Deployment
metadata:
    name: example-green
spec:
    selector:
        matchLabels:
            app: example
            env: green
    replicas: 2
    template:
        metadata:
            labels:
                app: example
                env: green
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Never
                  image: dipak:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: example-green
spec:
    selector:
        app: example
        env: green
    ports:
        - port: 5000
          targetPort: 5000
         
